---
:verbose: false
:concurrency: 1
:timeout: 25
:pidfile: tmp/pids/sidekiq.pid

:queues:
  - default
  - low

staging:
  :concurrency: 10

production:
  :concurrency: 25
  :timeout: 30
  :queues:
    - default
    - mailers
    - high_priority
