---
:verbose: false
:concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - default

production:
  :concurrency: 25
  logfile: /var/log/sidekiq.log

staging:
  :concurrency: 15
  logfile: /var/log/sidekiq.log
