name: Deploy on Merge to Master

on:
  push:
    branches: [main, 240124/github_action]
  workflow_dispatch:

jobs:
  deploy:
    name: Capistrano Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      # - name: Run Tests
      #   run: |
      #     bundle exec rspec
      #     export RSPEC_EXIT_CODE=$?
      #     if [ $RSPEC_EXIT_CODE -ne 0 ]; then
      #       echo "RSpec failed. Deployment halted."
      #       exit $RSPEC_EXIT_CODE
      #     fi

      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions
          known_hosts: ${{ secrets.KNOWN_HOSTS_OF_BASTION }}
          config: |
            host bastion
              HostName ${{ secrets.SERVER_PORT }}
              User ${{ secrets.SERVER_USER }}
              IdentityFile ~/.ssh/github-actions
              IdentitiesOnly yes
              ForwardAgent yes
              Host bastion

      - name: Adding Known Hosts
        run: echo ${{ secrets.KNOWN_HOSTS_OF_BASTION }} > ~/.ssh/known_hosts

      - name: Adding ssh
        run: echo ${{ secrets.SSH_KEY }} > ~/.ssh/github
      # ssh-keyscan -H ${{ secrets.SERVER_PORT }} >> ~/.ssh/known_hosts

      - name: Debug Known Hosts
        run: cat ~/.ssh/known_hosts

      - name: Debug Host Key
        run: cat ~/.ssh/github-actions

      - name: Deploy to production
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          bundle exec cap production deploy
